### ISSUE TITLE
new issue re: negative % amounts

### ISSUE THREAD

**Issue by Christopher-O** [gc-proto/covid-19-guidance#32]
@Borges-Porteous none of the rate amounts should be able to be negative (0% is the lowest). Currently I can calculate a negative amount for the three-month revenue drop at C2. I also broke it by entering very high numbers in the 2020 months (it told me the safe harbour rule would kick in). Maybe you're aware; wanted to flag

_Originally posted by @LMElston in https://github.com/gc-proto/covid-19-guidance/issues/18#issuecomment-667584376_

**Comment by Borges-Porteous** [comment]
Ah, good catches... Hmm, not sure what could cause the high amounts, there should still have to be a 30% drop.

I remember adding a negative numbers fix, but maybe it was just for one part... I'll go update.

**Comment by Borges-Porteous** [comment]
Huh, so I'm reviewing the code, and it looks correct to my eyes and mathematics... not that that's anything to trust, considering I'm a historian...

@Michel-Tremblay I might need your help with this, as it's already coded with what I would do to address the issue...

the math.max here is to avoid negative numbers in the rates:
//get the base rate
baseRate = parseFloat(Math.max(getP5PlusBaseRate(revReduction), 0));
//get the top-up rate
topUpRate = parseFloat(Math.max(getP5PlusTopUpRate(threeMonthReduction), 0));

The revReduction appears to be calculating the percentage drop correctly...
revReduction = Math.max(
   (baseRev - claimMonthValue) / baseRev,
   (baseRev - prevClaimValue) / baseRev
);

So what would cause something like this:
<img width="410" alt="Screen Shot 2020-08-01 at 8 08 30 PM" src="https://user-images.githubusercontent.com/22773687/89112647-bac33f80-d433-11ea-94d2-1a7ef057a8d3.png">

**Comment by LMElston** [comment]
I can still break it if I add really huge numbers (1M+). But maybe it’s an outside case that would be entering 7 figures?

[cid:image001.png@01D66849.5494FD80]

Laura May

Digital Design and Production Directorate (DDPD) | Direction de la conception et de la production numériques (DCPN)
Telephone | Téléphone 416-523-1072

**Comment by Michel-Tremblay** [comment]
we're doing ```Math.max(x, 0)``` on the ```baseRate```, ```topUpRate``` and ```revReduction``` but C2 and the summary was updated to use the value of the ```threeMonthReduction```. Would this fix it?
```js
Math.max(threeMonthReduction, 0) 
```

when displaying the variables?

**Comment by Michel-Tremblay** [comment]
i fixed an issue in the 2020-2019 calculations. there was a syntax error from removing the formatted value change from yesterday

![image](https://user-images.githubusercontent.com/11430547/89125310-973bdb80-d4ab-11ea-903b-714597f10538.png)

**Comment by Borges-Porteous** [comment]
> we're doing `Math.max(x, 0)` on the `baseRate`, `topUpRate` and `revReduction` but C2 and the summary was updated to use the value of the `threeMonthReduction`. Would this fix it?
> 
> ```js
> Math.max(threeMonthReduction, 0) 
> ```
> 
> when displaying the variables?

Thanks for adding that to the threeMonthReduction, but I don't believe it solved the issue... 

I'm still getting the 100% revenue drop even when it's obviously not (see my screenshot above) and I'm even getting a 3 month revenue drop that's negative when I modify the July field, that shouldn't even be part of the 3 month revenue drop calculation... 

Sent you an email - would be great if we can discuss. 

I'm quite baffled at what's going on, as I can't 'see' it in the code... there is more than one bug here, hope it's all tangled together and we can identify and fix the issue.

**Comment by Borges-Porteous** [comment]
So I've pushed the update:

- It now truncates the cews rate *1000 and then divides by 100
- The employees hide is in a separate if statement, so will still trigger the display updates, which was causing that other error

Still haven't tested or double checked, since I have to step away, but if anyone has a chance, would be great if you can have a look... and try some more numbers, in either the corresponding month of 2019 or Jan-Feb baseline for the %s
